version: '3.7'

services:
  clickhouse:
    image: kernel528/clickhouse-server:25.5.2.47
    user: "1024:100"
    container_name: clickhouse
    environment:
      CLICKHOUSE_SKIP_USER_SETUP: 1 # This allows insecure default user
    ports:
      - "8123:8123" # HTTP interface
      - "19000:9000" # Native client
    volumes:
      - clickhouse-data:/var/lib/clickhouse
      - clickhouse-config:/etc/clickhouse-server
    restart: unless-stopped

volumes:
  clickhouse-data:
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=scarif,rw"
      device: ":/volume1/docker-swarm/clickhouse_data"
  clickhouse-config:
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=scarif,rw"
      device: ":/volume1/docker-swarm/clickhouse_config"
