version: '3.7'

services:
  clickhouse:
    image: clickhouse/clickhouse-server:25.1.5.31-alpine
    container_name: clickhouse
    environment:
      CLICKHOUSE_SKIP_USER_SETUP: 1 # This allows insecure default user
    ports:
      - "8123:8123" # HTTP interface
      - "19000:9000" # Native client
    volumes:
      - clickhouse-data:/var/lib/clickhouse
      - clickhouse-config:/etc/clickhouse-server
    restart: unless-stopped

volumes:
  clickhouse-data:
  clickhouse-config: